-- V8__Insert_kiwi_category_data.sql

-- 向现有的 product 表插入猕猴桃数据
INSERT INTO product (
    name, english_name, short_description, description, 
    category_type, base_price, weight_unit, main_image_url, 
    is_featured, is_active, sort_order, origin,
    sweetness_level, acidity_level, kiwi_variety, vitamin_c_content, skin_type, harvest_season,
    storage_method, shelf_life, nutritional_info, tags, season,
    created_at, updated_at
) VALUES 
(
    '秦岭猕猴桃', 
    'qinling-kiwi', 
    '果肉翠绿，酸甜适中，营养丰富', 
    '秦岭猕猴桃产自秦岭山脉，果肉翠绿，酸甜适中，富含维生素C和膳食纤维。每一颗都经过精心挑选，确保品质上乘。独特的地理环境造就了其卓越的口感和营养价值。',
    'FRUIT',
    15.8, 
    '500g',
    'https://d3sx9glhrpxv9q.cloudfront.net/kiwi.png', 
    true, 
    true, 
    1,
    '陕西秦岭',
    4, 
    3,
    '秦岭猕猴桃',
    '62mg/100g',
    'HAIRY',
    '9月-11月',
    '冷藏保存，避免挤压',
    '15天',
    '{"vitamin_c": "62mg", "dietary_fiber": "3.1g", "potassium": "312mg", "calories": "61", "sugar": "9g"}',
    '["猕猴桃", "秦岭", "维生素C"]',
    '秋季',
    NOW(),
    NOW()
),
(
    '黄金猕猴桃', 
    'golden-kiwi', 
    '果肉金黄，甜度高，口感细腻', 
    '黄金猕猴桃果肉呈金黄色，甜度更高，口感更加细腻。富含维生素C、E和多种矿物质，营养价值极高。果皮光滑，易于食用，是进口水果中的精品选择。',
    'FRUIT',
    22.8, 
    '500g',
    'https://d3sx9glhrpxv9q.cloudfront.net/golden-kiwi.jpg', 
    true, 
    true, 
    2,
    '新西兰',
    5, 
    2,
    '黄金猕猴桃',
    '85mg/100g',
    'SMOOTH',
    '全年',
    '冷藏保存，避免阳光直射',
    '20天',
    '{"vitamin_c": "85mg", "dietary_fiber": "2.8g", "potassium": "315mg", "calories": "63", "sugar": "12g"}',
    '["猕猴桃", "进口", "黄金"]',
    '全年',
    NOW(),
    NOW()
),
(
    '红心猕猴桃', 
    'red-kiwi', 
    '红心果肉，富含花青素，抗氧化', 
    '红心猕猴桃果肉呈鲜艳红色，富含花青素和抗氧化物质。口感酸甜平衡，果香浓郁，营养价值极高。是国内优质猕猴桃的代表品种，深受消费者喜爱。',
    'FRUIT',
    19.8, 
    '500g',
    'https://d3sx9glhrpxv9q.cloudfront.net/red-kiwi.jpg', 
    true, 
    true, 
    3,
    '四川苍溪',
    4, 
    3,
    '红心猕猴桃',
    '75mg/100g',
    'HAIRY',
    '10月-12月',
    '冷藏保存，避免挤压',
    '12天',
    '{"vitamin_c": "75mg", "dietary_fiber": "3.2g", "potassium": "290mg", "calories": "59", "sugar": "10g", "anthocyanin": "15mg"}',
    '["猕猴桃", "红心", "抗氧化"]',
    '秋冬',
    NOW(),
    NOW()
),
(
    '有机猕猴桃', 
    'organic-kiwi', 
    '有机种植，无农药残留，健康安全', 
    '有机猕猴桃采用有机种植方式，完全不使用化学农药和化肥。果实在自然环境中生长，味道纯正自然。通过有机认证，确保无农药残留，是追求健康生活人士的首选。',
    'FRUIT',
    25.5, 
    '500g',
    'https://d3sx9glhrpxv9q.cloudfront.net/organic-kiwi.jpg', 
    true, 
    true, 
    4,
    '陕西周至',
    4, 
    3,
    '有机猕猴桃',
    '70mg/100g',
    'HAIRY',
    '9月-11月',
    '冷藏保存',
    '15天',
    '{"vitamin_c": "70mg", "dietary_fiber": "3.4g", "potassium": "305mg", "calories": "58", "sugar": "9g"}',
    '["猕猴桃", "有机", "健康"]',
    '秋季',
    NOW(),
    NOW()
),
(
    '徐香猕猴桃', 
    'xuxiang-kiwi', 
    '果香浓郁，酸甜可口，品质稳定', 
    '徐香猕猴桃果形端正，果肉翠绿，果香浓郁。酸甜比例恰到好处，口感细腻，品质稳定。是国内市场上备受欢迎的猕猴桃品种之一。',
    'FRUIT',
    16.8, 
    '500g',
    'https://d3sx9glhrpxv9q.cloudfront.net/xuxiang-kiwi.jpg', 
    false, 
    true, 
    5,
    '陕西眉县',
    4, 
    3,
    '徐香猕猴桃',
    '68mg/100g',
    'HAIRY',
    '9月-11月',
    '冷藏保存',
    '14天',
    '{"vitamin_c": "68mg", "dietary_fiber": "3.0g", "potassium": "298mg", "calories": "60", "sugar": "10g"}',
    '["猕猴桃", "徐香", "国产"]',
    '秋季',
    NOW(),
    NOW()
),
(
    '海沃德猕猴桃', 
    'hayward-kiwi', 
    '果形标准，耐储存，商业主流', 
    '海沃德猕猴桃是国际上最主流的商业品种，果形标准，大小均匀。果肉翠绿，酸甜适中，耐储存运输。是全球猕猴桃市场的主要品种。',
    'FRUIT',
    14.8, 
    '500g',
    'https://d3sx9glhrpxv9q.cloudfront.net/hayward-kiwi.jpg', 
    false, 
    true, 
    6,
    '智利',
    3, 
    4,
    '海沃德猕猴桃',
    '60mg/100g',
    'HAIRY',
    '4月-10月',
    '冷藏保存',
    '30天',
    '{"vitamin_c": "60mg", "dietary_fiber": "2.9g", "potassium": "285mg", "calories": "57", "sugar": "8g"}',
    '["猕猴桃", "进口", "海沃德"]',
    '春夏秋',
    NOW(),
    NOW()
);

-- 避免重复插入的检查
DO $$
BEGIN
    -- 检查是否已经存在这些猕猴桃产品
    IF NOT EXISTS (SELECT 1 FROM product WHERE english_name = 'qinling-kiwi') THEN
        -- 数据已经在上面插入
    END IF;
END $$;